import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Atkinson_Hyperlegible_Next,
  Fascinate,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const atkinsonHyperlegible = Atkinson_Hyperlegible_Next({
  variable: "--font-atkinson-hyperlegible",
  subsets: ["latin"],
});

const fascinate = Fascinate({
  variable: "--font-fascinate",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${atkinsonHyperlegible.variable} ${fascinate.variable} h-full antialiased`}
    >
      <head>
        <meta name="darkreader-lock" />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
